pip install discord
pip install python-dotenv
pip install mysql-connector-python
pip install spotipy
pip install quart
pip install quart_discord
pip install better-ipc
pip install fastapi
pip install asyncio
pip install nest_asyncio